# Generated by Django 3.2.23 on 2023-11-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231123_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinee_answer',
            name='isbookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examinee_answer',
            name='iscorrect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examinee_answer',
            name='issubmitted',
            field=models.BooleanField(default=False),
        ),
    ]
