# Generated by Django 3.2.23 on 2023-11-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20231123_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinee_answer',
            name='examinee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Examinee',
        ),
    ]
