# Generated by Django 3.2.23 on 2023-11-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20231123_0841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(related_name='questions', to='core.Choice'),
        ),
    ]
