# Generated by Django 3.2.23 on 2023-11-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20231128_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('examinee', 'Examinee'), ('admin', 'Admin')], default='examinee', max_length=20),
        ),
    ]
