# Generated by Django 3.2.23 on 2023-11-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('examinee', 'Examinee'), ('admin', 'Admin'), ('super admin', 'Super Admin')], default='examinee', max_length=20),
        ),
    ]
